REPLACE INTO ?:yad_status_descriptions (yad_status_id, yad_status_name, lang_code) VALUES(0, 'Заказ доступен для редактирования', 'ru');
REPLACE INTO ?:yad_status_descriptions (yad_status_id, yad_status_name, lang_code) VALUES(1, 'Заказ находится на проверке', 'ru');
REPLACE INTO ?:yad_status_descriptions (yad_status_id, yad_status_name, lang_code) VALUES(2, 'Заказ не прошел проверку', 'ru');
REPLACE INTO ?:yad_status_descriptions (yad_status_id, yad_status_name, lang_code) VALUES(3, 'Заказ проверен и отправлен в службу доставки', 'ru');
REPLACE INTO ?:yad_status_descriptions (yad_status_id, yad_status_name, lang_code) VALUES(4, 'Заказ ожидает подтверждения от службы доставки', 'ru');
REPLACE INTO ?:yad_status_descriptions (yad_status_id, yad_status_name, lang_code) VALUES(5, 'Заказ подтвержден службой доставки', 'ru');
REPLACE INTO ?:yad_status_descriptions (yad_status_id, yad_status_name, lang_code) VALUES(6, 'Заказ ожидается на едином складе', 'ru');
REPLACE INTO ?:yad_status_descriptions (yad_status_id, yad_status_name, lang_code) VALUES(7, 'Заказ ожидается в службе доставки', 'ru');
REPLACE INTO ?:yad_status_descriptions (yad_status_id, yad_status_name, lang_code) VALUES(8, 'Заказ находится на складе службы доставки', 'ru');
REPLACE INTO ?:yad_status_descriptions (yad_status_id, yad_status_name, lang_code) VALUES(9, 'Заказ находится на сортировке в службе доставки', 'ru');
REPLACE INTO ?:yad_status_descriptions (yad_status_id, yad_status_name, lang_code) VALUES(10, 'Заказ доставляется', 'ru');
REPLACE INTO ?:yad_status_descriptions (yad_status_id, yad_status_name, lang_code) VALUES(11, 'Заказ находится в населенном пункте получателя', 'ru');
REPLACE INTO ?:yad_status_descriptions (yad_status_id, yad_status_name, lang_code) VALUES(12, 'Заказ доставляется по населенному пункту получателя', 'ru');
REPLACE INTO ?:yad_status_descriptions (yad_status_id, yad_status_name, lang_code) VALUES(13, 'Заказ проходит таможенный контроль', 'ru');
REPLACE INTO ?:yad_status_descriptions (yad_status_id, yad_status_name, lang_code) VALUES(14, 'Заказ передан в доставку по России', 'ru');
REPLACE INTO ?:yad_status_descriptions (yad_status_id, yad_status_name, lang_code) VALUES(15, 'Заказ доставляется', 'ru');
REPLACE INTO ?:yad_status_descriptions (yad_status_id, yad_status_name, lang_code) VALUES(16, 'Заказ ожидается на едином складе', 'ru');
REPLACE INTO ?:yad_status_descriptions (yad_status_id, yad_status_name, lang_code) VALUES(17, 'Заказ ожидается в службе доставки', 'ru');
REPLACE INTO ?:yad_status_descriptions (yad_status_id, yad_status_name, lang_code) VALUES(18, 'Доставка перенесена службой доставки', 'ru');
REPLACE INTO ?:yad_status_descriptions (yad_status_id, yad_status_name, lang_code) VALUES(19, 'Заказ находится на складе службы доставки', 'ru');
REPLACE INTO ?:yad_status_descriptions (yad_status_id, yad_status_name, lang_code) VALUES(20, 'Заказ находится в пункте самовывоза', 'ru');
REPLACE INTO ?:yad_status_descriptions (yad_status_id, yad_status_name, lang_code) VALUES(21, 'Заказ вручен клиенту', 'ru');
REPLACE INTO ?:yad_status_descriptions (yad_status_id, yad_status_name, lang_code) VALUES(22, 'Заказ доставлен получателю', 'ru');
REPLACE INTO ?:yad_status_descriptions (yad_status_id, yad_status_name, lang_code) VALUES(23, 'Неудачная попытка вручения заказа', 'ru');
REPLACE INTO ?:yad_status_descriptions (yad_status_id, yad_status_name, lang_code) VALUES(24, 'Заказ не может быть доставлен', 'ru');
REPLACE INTO ?:yad_status_descriptions (yad_status_id, yad_status_name, lang_code) VALUES(25, 'Заказ готовится к возврату', 'ru');
REPLACE INTO ?:yad_status_descriptions (yad_status_id, yad_status_name, lang_code) VALUES(26, 'Заказ возвращен на склад службы доставки', 'ru');
REPLACE INTO ?:yad_status_descriptions (yad_status_id, yad_status_name, lang_code) VALUES(27, 'Заказ передан на единый склад', 'ru');
REPLACE INTO ?:yad_status_descriptions (yad_status_id, yad_status_name, lang_code) VALUES(28, 'Заказ ожидает подтверждения от сортировочного центра', 'ru');
REPLACE INTO ?:yad_status_descriptions (yad_status_id, yad_status_name, lang_code) VALUES(29, 'Заказ подтвержден сортировочным центром', 'ru');
REPLACE INTO ?:yad_status_descriptions (yad_status_id, yad_status_name, lang_code) VALUES(30, 'Заказ поступил на склад сортировочного центра', 'ru');
REPLACE INTO ?:yad_status_descriptions (yad_status_id, yad_status_name, lang_code) VALUES(31, 'Некоторые позиции заказа отсутствуют на складе сортировочного центра', 'ru');
REPLACE INTO ?:yad_status_descriptions (yad_status_id, yad_status_name, lang_code) VALUES(32, 'Отправлен запрос на создание заказа в системе службы доставки', 'ru');
REPLACE INTO ?:yad_status_descriptions (yad_status_id, yad_status_name, lang_code) VALUES(33, 'Заказ создан в системе службы доставки', 'ru');
REPLACE INTO ?:yad_status_descriptions (yad_status_id, yad_status_name, lang_code) VALUES(34, 'Отправлен запрос на создание заказа в системе сортировочного центра.', 'ru');
REPLACE INTO ?:yad_status_descriptions (yad_status_id, yad_status_name, lang_code) VALUES(35, 'Заказ создан в системе сортировочного центра', 'ru');
REPLACE INTO ?:yad_status_descriptions (yad_status_id, yad_status_name, lang_code) VALUES(36, 'Ожидаются уточнения по заказу в сортировочном центре', 'ru');
REPLACE INTO ?:yad_status_descriptions (yad_status_id, yad_status_name, lang_code) VALUES(37, 'Заказ на складе сортировочного центра подготовлен к отправке в службу доставки', 'ru');
REPLACE INTO ?:yad_status_descriptions (yad_status_id, yad_status_name, lang_code) VALUES(38, 'Заказ отгружен сортировочным центром в службу доставки', 'ru');
REPLACE INTO ?:yad_status_descriptions (yad_status_id, yad_status_name, lang_code) VALUES(39, 'Сортировочный центр получил данные о планируемом возврате заказа', 'ru');
REPLACE INTO ?:yad_status_descriptions (yad_status_id, yad_status_name, lang_code) VALUES(40, 'Возвратный заказ готов к передаче в сортировочный центр.', 'ru');
REPLACE INTO ?:yad_status_descriptions (yad_status_id, yad_status_name, lang_code) VALUES(41, 'Возвратный заказ передан в сортировочный центр', 'ru');
REPLACE INTO ?:yad_status_descriptions (yad_status_id, yad_status_name, lang_code) VALUES(42, 'Возвратный заказ поступил на склад сортировочного центра', 'ru');
REPLACE INTO ?:yad_status_descriptions (yad_status_id, yad_status_name, lang_code) VALUES(43, 'Возвратный заказ на складе сортировочного центра', 'ru');
REPLACE INTO ?:yad_status_descriptions (yad_status_id, yad_status_name, lang_code) VALUES(44, 'Возвратный заказ готов для передачи магазину', 'ru');
REPLACE INTO ?:yad_status_descriptions (yad_status_id, yad_status_name, lang_code) VALUES(45, 'Возвратный заказ на складе сортировочного центра.', 'ru');
REPLACE INTO ?:yad_status_descriptions (yad_status_id, yad_status_name, lang_code) VALUES(46, 'Заказ возвращен в магазин', 'ru');
REPLACE INTO ?:yad_status_descriptions (yad_status_id, yad_status_name, lang_code) VALUES(47, 'Заказ отменен', 'ru');
REPLACE INTO ?:yad_status_descriptions (yad_status_id, yad_status_name, lang_code) VALUES(48, 'Ошибка создания заказа в сортировочном центре', 'ru');
REPLACE INTO ?:yad_status_descriptions (yad_status_id, yad_status_name, lang_code) VALUES(49, 'Заказ утерян в процессе доставки', 'ru');
REPLACE INTO ?:yad_status_descriptions (yad_status_id, yad_status_name, lang_code) VALUES(50, 'Статус заказа уточняется', 'ru');
REPLACE INTO ?:yad_status_descriptions (yad_status_id, yad_status_name, lang_code) VALUES(51, 'Заказ отменен', 'ru');
REPLACE INTO ?:yad_status_descriptions (yad_status_id, yad_status_name, lang_code) VALUES(52, 'Заказ отменен покупателем', 'ru');
REPLACE INTO ?:yad_status_descriptions (yad_status_id, yad_status_name, lang_code) VALUES(53, 'Финальный статус заказа', 'ru');
REPLACE INTO ?:yad_status_descriptions (yad_status_id, yad_status_name, lang_code) VALUES(54, 'Ошибка создания заказа', 'ru');
REPLACE INTO ?:yad_status_descriptions (yad_status_id, yad_status_name, lang_code) VALUES(55, 'Ошибка обработки заказа', 'ru');
REPLACE INTO ?:yad_status_descriptions (yad_status_id, yad_status_name, lang_code) VALUES(56, 'Заказ не найден', 'ru');